name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2

  flutter_svg: ^0.15.0
  simple_animations: ^1.3.4
  vector_math: any
  gradient_text: ^1.0.2
  tinycolor: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: clock2
      fonts:
        - asset: assets/clock2/clock2.ttf
    - family: roboto-mono
      fonts:
        - asset: assets/Roboto_Mono/RobotoMono-Regular.ttf
          weight: 600
  assets:
    - assets/
